/**
 * RhymeSuggester — local, dictionary-based rhyme + semantic suggestions.
 *
 * Public API
 * ──────────
 *   score(lineData, allLines)
 *     Scores every candidate word against the current line's IPA ending and
 *     the lyrics' semantic context.  Returns:
 *       { candidates: [{word, phoneNorm, semNorm}], hasEmbeddings: bool }
 *     phoneNorm and semNorm are each independently normalised to [0, 1].
 *     Expensive on first call; result should be cached by the caller.
 *
 *   rank(candidates, weight, n = 12)
 *     Pure ranking — no async, no re-scoring.
 *     weight 0 → 100 % phonetics, weight 1 → 100 % semantics.
 *     Returns string[] of length ≤ n.
 *
 * Modes
 * ─────
 *   FULL  – data/words_{lang}.js loaded (generated by build script).
 *            100 k-word vocabulary with 50 d word embeddings.
 *            semNorm = cosine similarity to the mean lyrics embedding, clamped
 *            to [0, 1] and normalised by the observed max across candidates.
 *
 *   BASIC – always available, no build step.
 *            ~300-word embedded vocabulary, IPA via IpaConverter.
 *            semNorm = 1 if word's category appears in existing lyrics, else 0.
 *            Slider still works; semantic signal is coarser.
 */
const RhymeSuggester = (() => {

  // ── Embedded fallback vocabulary ─────────────────────────────────────────
  const FALLBACK = {
    fr: {
      amour: [
        'amour','toujours','retour','secours','velours','parcours','discours',
        'jour','tour','autour','tambour','carrefour','contour','détour',
        'cœur','peur','fleur','douleur','bonheur','chaleur','malheur','sœur',
        'ardeur','lueur','erreur','valeur','couleur','hauteur','douceur',
        'ferveur','vapeur','fureur','grandeur','fraîcheur','langueur',
        'tendresse','caresse','promesse','jeunesse','ivresse','détresse','faiblesse',
        'désir','soupir','subir','chérir','languir','finir','partir','fuir','venir',
        'tenir','saisir','souvenir','avenir','mourir','courir','agir','bâtir',
      ],
      nuit: [
        'nuit','bruit','fuite','pluie','conduit','minuit','suite','ennui',
        'soir','voir','espoir','pouvoir','savoir','avoir','devoir','boire',
        'mémoire','gloire','victoire','histoire','ivoire','miroir','armoire',
        'ombre','nombre','sombre','décombre','encombre',
        'monde','seconde','profonde','abonde','correspond',
      ],
      destin: [
        'chemin','matin','destin','jardin','satin','chagrin','voisin',
        'coussin','raisin','lutin','divin','festin','assassin','bassin',
        'lapin','moulin','patin','coquin','magasin','tocsin',
        'demain','lointain','soudain','humain','certain','prochain',
        'main','pain','train','gain','vain','bain','sain','grain',
      ],
      nature: [
        'soleil','sommeil','éveil','réveil','vermeil','orteil','conseil',
        'vent','enfant','printemps','chant','avant','vivant','courant',
        'partant','instant','devant','pendant','cependant','dedans',
        'moment','tourment','sentiment','mouvement','serment','élément',
        'mer','clair','fer','enfer','hiver','univers','amer','fier','léger',
        'cher','entier','dernier','premier','sanglier',
      ],
      âme: [
        'âme','femme','flamme','drame','programme',
        'larme','charme','alarme','arme',
        'vie','envie','folie','jolie','mélodie','magie','génie','énergie',
        'mélancolie','poésie','symphonie','harmonie','jalousie',
        'route','doute','écoute','goutte','voûte','croûte','lutte','butte',
      ],
      voix: [
        'voix','moi','toi','roi','loi','foi','joie','soie','croix','bois','doigt',
        'chanson','raison','maison','saison','horizon','prison','trahison',
        'oraison','floraison','liaison','comparaison',
        'nom','son','bon','don','fond','long','rond','ton','mon','non',
      ],
      rêve: [
        'rêve','grève','sève','trêve','brève','lève','élève',
        'silence','danse','lance','chance','distance','souffrance',
        'enfance','romance','espérance','croissance','naissance',
        'puissance','renaissance','confiance','élégance',
        'peine','scène','reine','pleine','veine','haleine','fontaine',
        'chaîne','laine','semaine','baleine','prochaine',
      ],
      lumière: [
        'lumière','manière','matière','rivière','frontière','entière',
        'prière','carrière','barrière','clairière',
        'ciel','miel','réel','tel','sel','gel','bel','quel','appel',
        'éternel','immortel','sensuel','virtuel','habituel','mutuel',
        'feu','bleu','lieu','vœu','jeu','peu','pieu','aveu','neveu',
      ],
    },
    en: {
      night: [
        'night','light','bright','sight','might','right','fight','white',
        'flight','delight','ignite','invite','tonight','moonlight','starlight',
        'twilight','midnight','recite','despite','alight','unite','quite',
        'bite','kite','rite','write','smite','finite','polite',
      ],
      day: [
        'day','way','say','stay','play','ray','lay','pray','away',
        'today','betray','decay','delay','display','relay','stray','sway',
        'grey','they','prey','weigh','name','flame','frame','claim',
        'game','same','tame','blame','came','shame','fame',
        'rain','pain','gain','vain','main','remain','explain','refrain',
        'sustain','chain','plain','strain','contain','terrain','complain',
      ],
      love: [
        'love','above','dove','glove',
        'heart','start','apart','art','chart','smart','depart','impart','dart',
        'soul','whole','goal','role','control','toll','roll','stroll','console',
        'dream','stream','gleam','beam','seem','cream','esteem','extreme','scheme',
        'desire','fire','higher','wire','inspire','entire','admire','require',
        'mine','line','shine','divine','wine','vine','fine','design','decline',
        'intertwine','define','combine','confine','assign','refine',
      ],
      sky: [
        'sky','fly','high','cry','die','lie','try','why','sigh','reply',
        'defy','deny','imply','supply','rely','comply','butterfly',
        'by','my','eye','tie','pie','rye','shy','spy','sly','nigh',
      ],
      time: [
        'time','rhyme','chime','climb','prime','sublime','lifetime',
        'mind','find','kind','behind','blind','bind','signed','defined',
        'rewind','remind','combined','mankind','refined',
        'deep','sleep','weep','keep','sweep','leap','creep','steep',
        'reap','cheap','heap','seep','peep',
      ],
      free: [
        'free','sea','be','tree','see','plea','me','key','agree','degree',
        'believe','leave','breathe','grieve','receive','achieve','perceive',
        'relieve','retrieve','conceive','deceive','weave','cleave',
        'road','alone','stone','home','roam','foam','known','grown',
        'shown','blown','throne','zone','bone','tone','phone','gone',
        'moan','groan','loan','clone','prone','hone',
      ],
      sound: [
        'sound','ground','found','around','bound','profound','surround','astound',
        'end','friend','blend','bend','send','mend','spend','defend','extend',
        'ascend','attend','depend','pretend','transcend','offend','amend',
        'long','song','strong','belong','along','dawn','born','torn','worn',
        'sworn','mourn','horn','corn','scorn','warn','forlorn',
      ],
      rain: [
        'fade','shade','made','blade','trade','cascade','pervade','afraid',
        'evade','invade','parade','charade','decade','grenade','masquerade',
        'break','lake','wake','make','take','sake','shake','bake','cake',
        'fake','rake','snake','stake','flake','quake','partake','forsake',
      ],
    },
    es: {
      amor: [
        'amor','calor','dolor','valor','flor','color','ardor','temblor',
        'clamor','rumor','honor','fervor','fulgor','pudor','primor',
        'vida','herida','guarida','partida','querida','medida','venida',
        'salida','elegida','perdida','avenida','bienvenida',
      ],
      noche: [
        'noche','broche','derroche','reproche','coche',
        'cielo','suelo','vuelo','anhelo','consuelo','velo','duelo',
        'desvelo','abuelo','modelo','pelo','hielo','anzuelo',
        'tiempo','viento','momento','tormento','aliento','cuento',
        'intento','cimiento','contento','talento','portento',
      ],
      alma: [
        'alma','calma','palma',
        'luna','fortuna','ninguna','laguna','tribuna','columna',
        'sueño','empeño','dueño','ensueño','desempeño','pequeño',
        'canción','razón','corazón','ilusión','pasión','emoción',
        'oración','nación','traición','estación','creación','solución',
      ],
      fuego: [
        'fuego','juego','ruego','sosiego','apego',
        'sol','col','rol','control','caracol','español',
        'voz','feroz','veloz','atroz','precoz',
      ],
    },
    it: {
      amore: [
        'amore','cuore','dolore','calore','valore','fiore','colore',
        'ardore','terrore','furore','onore','errore','sapore','favore',
        'tremore','splendore','candore','orrore','stupore','rumore',
        'vita','ferita','infinita','unita','ambita','sentita','salita',
        'partita','gratuita','smarrita','tradita',
      ],
      notte: [
        'notte','grotte','rotte','botte','lotte','dotte',
        'luna','fortuna','bruna','laguna','tribuna','duna',
        'voce','croce','noce','atroce','feroce','precoce','veloce',
      ],
      cielo: [
        'cielo','velo','gelo','bello','quello','anello',
        'castello','uccello','capello','fratello','martello','coltello',
        'sogno','bisogno','ingegno','legno','segno','pegno','degno',
        'tempo','sempre','insieme','estremo','sistema','problema',
      ],
      cuore: [
        'core','ancora','aurora','dimora','signora','lavora','adora',
        'mare','pare','amare','sperare','trovare','pensare','chiamare',
        'guardare','cercare','tornare','parlare','cantare','volare',
      ],
    },
  };

  // ── IPA normalisation (mirrors RhymeDetector.cleanIpa) ──────────────────
  function _cleanIpa(s) {
    return (s || '')
      .replace(/[ˈˌ\/\[\]ː]/g, '')
      .replace(/z/g, 's').replace(/d/g, 't').replace(/b/g, 'p')
      .replace(/ɡ/g, 'k').replace(/v/g, 'f').replace(/ð/g, 'θ')
      .replace(/ʒ/g, 'ʃ').replace(/ə$/, '').trim();
  }

  function _suffixLen(a, b) {
    let i = a.length - 1, j = b.length - 1, n = 0;
    while (i >= 0 && j >= 0 && a[i] === b[j]) { n++; i--; j--; }
    return n;
  }

  // ── Fallback: embedded vocabulary + IpaConverter ─────────────────────────
  const _fbCache    = {};
  const _fbBuilding = {};

  async function _buildFallbackCache(lang) {
    if (_fbCache[lang]) return;
    if (_fbBuilding[lang]) {
      await new Promise((res) => {
        const t = setInterval(() => { if (!_fbBuilding[lang]) { clearInterval(t); res(); } }, 50);
      });
      return;
    }
    _fbBuilding[lang] = true;
    const allWords = [...new Set(Object.values(FALLBACK[lang] || {}).flat())];
    const ipaWords = await IpaConverter.convertLine(allWords.join(' '), lang);
    const map = new Map();
    allWords.forEach((w, i) => map.set(w, _cleanIpa(ipaWords[i]?.ipa || '')));
    _fbCache[lang] = map;
    _fbBuilding[lang] = false;
  }

  function _detectCategories(allLines, currentLine, lang) {
    const cats = FALLBACK[lang] || {};
    const lyricText = allLines
      .filter((l) => l !== currentLine && l.text.trim())
      .map((l) => l.text.toLowerCase()).join(' ');
    const matched = new Set();
    for (const [cat, words] of Object.entries(cats)) {
      if (words.some((w) => lyricText.includes(w.toLowerCase()))) matched.add(cat);
    }
    return matched;
  }

  async function _scoreFallback(lineData, allLines, targetIpa) {
    const { lang, text } = lineData;
    if (!FALLBACK[lang]) return null;
    await _buildFallbackCache(lang);

    const cache      = _fbCache[lang];
    const target     = _cleanIpa(targetIpa);
    if (!target) return { candidates: [], hasEmbeddings: false };

    const categories = _detectCategories(allLines, lineData, lang);
    const hasContext = categories.size > 0;
    const currentText = text.toLowerCase();
    const cats = FALLBACK[lang];

    // Raw scores
    const raw = [];
    for (const [cat, words] of Object.entries(cats)) {
      for (const word of words) {
        if (currentText.includes(word.toLowerCase())) continue;
        const phoneRaw = _suffixLen(target, cache.get(word) || '');
        const semRaw   = hasContext ? (categories.has(cat) ? 1 : 0) : 0.5;
        raw.push({ word, phoneRaw, semRaw });
      }
    }

    return _normalise(raw, false);
  }

  // ── Full path: pre-built data + embeddings ────────────────────────────────
  const _index   = {};
  const _loading = {};

  function _getData(lang) {
    return window[`WORD_DATA_${lang.toUpperCase()}`] || null;
  }

  function _loadData(lang) {
    if (_getData(lang)) return Promise.resolve(true);
    if (_loading[lang]) return _loading[lang];
    _loading[lang] = new Promise((resolve) => {
      const s = document.createElement('script');
      s.src = `data/words_${lang}.js`;
      s.onload  = () => resolve(true);
      s.onerror = () => resolve(false);
      document.head.appendChild(s);
    });
    return _loading[lang];
  }

  function _buildIndex(lang) {
    if (_index[lang]) return;
    const d = _getData(lang);
    if (!d) return;
    const m = new Map();
    d.words.forEach((w, i) => m.set(w.toLowerCase(), i));
    _index[lang] = m;
  }

  function _getVec(data, idx) {
    return data.vecs.subarray(idx * data.dim, (idx + 1) * data.dim);
  }

  function _cosineSim(a, b) {
    let dot = 0, na = 0, nb = 0;
    for (let i = 0; i < a.length; i++) { dot += a[i]*b[i]; na += a[i]*a[i]; nb += b[i]*b[i]; }
    const denom = Math.sqrt(na) * Math.sqrt(nb);
    return denom < 1e-9 ? 0 : dot / denom;
  }

  function _lyricsVector(allLines, currentLine, data, index) {
    const sum = new Float32Array(data.dim);
    let count = 0;
    for (const line of allLines) {
      if (line === currentLine || !line.text.trim()) continue;
      for (const tok of line.text.toLowerCase()
          .split(/[\s\-'']+/)
          .map((t) => t.replace(/[^a-zA-ZÀ-ÿœŒ\u0100-\u024F]/g, ''))
          .filter(Boolean)) {
        const idx = index.get(tok);
        if (idx === undefined) continue;
        const vec = _getVec(data, idx);
        for (let i = 0; i < data.dim; i++) sum[i] += vec[i];
        count++;
      }
    }
    if (count > 0) for (let i = 0; i < data.dim; i++) sum[i] /= count;
    return { vec: sum, count };
  }

  async function _scoreFull(lineData, allLines, data, targetIpa) {
    _buildIndex(lineData.lang);
    const index  = _index[lineData.lang];
    const target = _cleanIpa(targetIpa);
    if (!target) return { candidates: [], hasEmbeddings: true };

    const { vec: lyricsVec, count } = _lyricsVector(allLines, lineData, data, index);
    const hasContext   = count > 0;
    const currentText  = lineData.text.toLowerCase();
    const N = data.words.length;
    const raw = [];

    for (let i = 0; i < N; i++) {
      const word = data.words[i];
      if (currentText.includes(word.toLowerCase())) continue;
      const phoneRaw = _suffixLen(target, _cleanIpa(data.ipa[i] || ''));
      // cosine sim ∈ [-1, 1] → clamp to [0, 1]
      const semRaw = hasContext
        ? Math.max(0, _cosineSim(lyricsVec, _getVec(data, i)))
        : 0;
      raw.push({ word, phoneRaw, semRaw });
    }

    return _normalise(raw, true);
  }

  // ── Normalisation ────────────────────────────────────────────────────────
  // Independently normalise phoneRaw and semRaw to [0, 1] by dividing each by
  // its observed maximum across all candidates.
  function _normalise(raw, hasEmbeddings) {
    if (raw.length === 0) return { candidates: [], hasEmbeddings };

    let maxPhone = 0, maxSem = 0;
    for (const r of raw) {
      if (r.phoneRaw > maxPhone) maxPhone = r.phoneRaw;
      if (r.semRaw   > maxSem)   maxSem   = r.semRaw;
    }

    const candidates = raw.map(({ word, phoneRaw, semRaw }) => ({
      word,
      phoneNorm: maxPhone > 0 ? phoneRaw / maxPhone : 0,
      semNorm:   maxSem   > 0 ? semRaw   / maxSem   : 0,
    }));

    return { candidates, hasEmbeddings };
  }

  // ── Public API ────────────────────────────────────────────────────────────

  /**
   * Score all candidate words against the current line (or a custom target word).
   * targetWord — optional override; if omitted the last word of lineData.text is used.
   * Returns { candidates: [{word, phoneNorm, semNorm}], hasEmbeddings }.
   * Cache the result; call rank() to re-sort without re-scoring.
   */
  async function score(lineData, allLines, targetWord = null) {
    await _loadData(lineData.lang);
    const data = _getData(lineData.lang);

    // Resolve the IPA for the rhyme-target word
    const word = (targetWord || '').trim() ||
      lineData.text.trim().split(/\s+/).pop() || '';
    let targetIpa = lineData.ipa || '';
    if (word) {
      const res = await IpaConverter.convertLine(word, lineData.lang);
      targetIpa = res[0]?.ipa || targetIpa;
    }

    if (data) return _scoreFull(lineData, allLines, data, targetIpa);
    return _scoreFallback(lineData, allLines, targetIpa);
  }

  /**
   * Pure ranking — no async, instant.
   * weight: 0 = 100 % phonetics, 1 = 100 % semantics.
   * Returns string[] of length ≤ n.
   */
  function rank(candidates, weight, n = 12) {
    const w = Math.max(0, Math.min(1, weight));
    return candidates
      .map((c) => ({ word: c.word, total: (1 - w) * c.phoneNorm + w * c.semNorm }))
      .sort((a, b) => b.total - a.total)
      .slice(0, n)
      .map((c) => c.word);
  }

  return { score, rank };
})();
