/**
 * RhymeSuggester — local, dictionary-based rhyme + lexical-field suggestions.
 *
 * Two modes, chosen automatically:
 *
 *   FULL  – when data/words_{lang}.js is loaded (generated by the build script).
 *            Uses a 7 000-word vocabulary with 50d word embeddings for semantic
 *            similarity.  Rich rhymes = longest IPA suffix; thematic = 40 %
 *            phonetics + 60 % cosine similarity to the lyrics context.
 *
 *   BASIC – always available, no build step needed.
 *            Uses an embedded ~300-word curated vocabulary per language whose IPA
 *            is computed on demand by the existing IpaConverter.  Thematic ranking
 *            uses lexical-field category detection (which category keywords appear
 *            in the existing lyrics).
 */
const RhymeSuggester = (() => {

  // ── Curated fallback vocabulary ──────────────────────────────────────────
  // Organised by language → semantic category → words.
  // Category detection: if a word from a category appears anywhere in the
  // existing lyrics, suggestions from that category are ranked higher.
  const FALLBACK = {
    fr: {
      amour: [
        'amour','toujours','retour','secours','velours','parcours','discours',
        'jour','tour','autour','tambour','carrefour','contour','détour',
        'cœur','peur','fleur','douleur','bonheur','chaleur','malheur','sœur',
        'ardeur','lueur','erreur','valeur','couleur','hauteur','douceur',
        'ferveur','vapeur','fureur','grandeur','fraîcheur','langueur',
        'tendresse','caresse','promesse','jeunesse','ivresse','détresse','faiblesse',
        'désir','soupir','subir','chérir','languir','finir','partir','fuir','venir',
        'tenir','saisir','souvenir','avenir','mourir','courir','agir','bâtir',
      ],
      nuit: [
        'nuit','bruit','fuite','pluie','conduit','minuit','suite','ennui',
        'soir','voir','espoir','pouvoir','savoir','avoir','devoir','boire',
        'mémoire','gloire','victoire','histoire','ivoire','miroir','armoire',
        'ombre','nombre','sombre','décombre','encombre',
        'monde','seconde','profonde','abonde','correspond',
      ],
      destin: [
        'chemin','matin','destin','jardin','satin','chagrin','voisin',
        'coussin','raisin','lutin','divin','festin','assassin','bassin',
        'lapin','moulin','patin','coquin','magasin','tocsin',
        'demain','lointain','soudain','humain','certain','prochain',
        'main','pain','train','gain','vain','bain','sain','grain',
      ],
      nature: [
        'soleil','sommeil','éveil','réveil','vermeil','orteil','conseil',
        'vent','enfant','printemps','chant','avant','vivant','courant',
        'partant','instant','devant','pendant','cependant','dedans',
        'moment','tourment','sentiment','mouvement','serment','élément',
        'mer','clair','fer','enfer','hiver','univers','amer','fier','léger',
        'cher','entier','dernier','premier','dernier','sanglier',
      ],
      âme: [
        'âme','femme','flamme','drame','programme',
        'larme','charme','alarme','arme',
        'vie','envie','folie','jolie','mélodie','magie','génie','énergie',
        'mélancolie','poésie','symphonie','harmonie','jalousie','bourgeoisie',
        'route','doute','écoute','goutte','voûte','croûte','lutte','butte',
      ],
      voix: [
        'voix','moi','toi','roi','loi','foi','joie','soie','croix','bois','doigt',
        'chanson','raison','maison','saison','horizon','prison','trahison',
        'oraison','floraison','liaison','comparaison',
        'nom','son','bon','don','fond','long','rond','ton','mon','non',
      ],
      rêve: [
        'rêve','grève','sève','trêve','brève','lève','élève',
        'silence','danse','lance','chance','distance','souffrance',
        'enfance','romance','espérance','croissance','naissance',
        'puissance','renaissance','confiance','élégance','brillance',
        'peine','scène','reine','pleine','veine','haleine','fontaine',
        'chaîne','laine','semaine','baleine','prochaine',
      ],
      lumière: [
        'lumière','manière','matière','rivière','frontière','entière',
        'prière','carrière','barrière','terrière','clairière',
        'ciel','miel','réel','tel','sel','gel','bel','quel','appel',
        'éternel','immortel','sensuel','virtuel','habituel','mutuel',
        'feu','bleu','lieu','vœu','jeu','peu','pieu','aveu','neveu',
      ],
    },

    en: {
      night: [
        'night','light','bright','sight','might','right','fight','white',
        'flight','delight','ignite','invite','tonight','moonlight','starlight',
        'twilight','midnight','recite','despite','alight','unite','ignite',
        'quite','bite','kite','rite','write','smite','finite','polite',
      ],
      day: [
        'day','way','say','stay','play','ray','lay','pray','away',
        'today','betray','decay','delay','display','relay','stray','sway',
        'grey','they','prey','weigh','name','flame','frame','claim',
        'game','same','tame','blame','came','shame','fame','claim',
        'rain','pain','gain','vain','main','remain','explain','refrain',
        'sustain','chain','plain','strain','contain','terrain','complain',
      ],
      love: [
        'love','above','dove','of','glove',
        'heart','start','apart','art','chart','smart','depart','impart','dart',
        'soul','whole','goal','role','control','toll','roll','stroll','console',
        'dream','stream','gleam','beam','seem','cream','esteem','extreme','scheme',
        'desire','fire','higher','wire','inspire','entire','admire','require',
        'mine','line','shine','divine','wine','vine','fine','design','decline',
        'intertwine','define','combine','confine','assign','refine',
      ],
      sky: [
        'sky','fly','high','cry','die','lie','try','why','sigh','reply',
        'defy','deny','imply','supply','rely','comply','July','butterfly',
        'by','my','eye','tie','pie','rye','shy','spy','sly','nigh',
      ],
      time: [
        'time','rhyme','chime','climb','prime','sublime','lifetime',
        'mind','find','kind','behind','blind','bind','signed','defined',
        'rewind','remind','combined','mankind','refined',
        'deep','sleep','weep','keep','sweep','leap','creep','steep',
        'reap','cheap','heap','seep','peep',
      ],
      free: [
        'free','sea','be','tree','see','plea','me','key','agree','degree',
        'believe','leave','breathe','grieve','receive','achieve','perceive',
        'relieve','retrieve','conceive','deceive','weave','cleave',
        'road','alone','stone','home','roam','foam','known','grown',
        'shown','blown','throne','zone','bone','tone','phone','gone',
        'moan','groan','loan','clone','prone','hone',
      ],
      sound: [
        'sound','ground','found','around','bound','profound','surround','astound',
        'end','friend','blend','bend','send','mend','spend','defend','extend',
        'ascend','attend','depend','pretend','transcend','offend','amend',
        'long','song','strong','belong','along','dawn','born','torn','worn',
        'sworn','mourn','horn','corn','scorn','warn','forlorn',
      ],
      rain: [
        'fade','shade','made','blade','trade','cascade','pervade','afraid',
        'evade','invade','parade','charade','decade','grenade','masquerade',
        'break','lake','wake','make','take','sake','shake','bake','cake',
        'fake','rake','snake','stake','flake','quake','partake','forsake',
      ],
    },

    es: {
      amor: [
        'amor','calor','dolor','valor','flor','color','ardor','temblor',
        'clamor','rumor','honor','fervor','fulgor','pudor','primor','tumor',
        'cantor','pastor','doctor','actor','factor','vector','sector',
        'vida','herida','guarida','partida','querida','medida','venida',
        'salida','elegida','perdida','avenida','bienvenida',
      ],
      noche: [
        'noche','broche','derroche','reproche','coche','moche',
        'cielo','suelo','vuelo','anhelo','consuelo','velo','duelo',
        'desvelo','abuelo','modelo','pelo','hielo','anzuelo',
        'tiempo','viento','momento','tormento','aliento','cuento',
        'intento','cimiento','contento','talento','portento','tormento',
      ],
      alma: [
        'alma','calma','palma',
        'luna','fortuna','ninguna','laguna','tribuna','columna',
        'sueño','empeño','dueño','ensueño','desempeño','pequeño',
        'canción','razón','corazón','ilusión','pasión','emoción',
        'oración','nación','traición','estación','creación','solución',
      ],
      fuego: [
        'fuego','juego','ruego','sosiego','apego','despego',
        'lejos','reflejos','espejos','consejos','añejos','festejos',
        'sol','col','rol','control','arból','caracol','español',
        'voz','adiós','feroz','veloz','atroz','feroz','precoz',
      ],
    },

    it: {
      amore: [
        'amore','cuore','dolore','calore','valore','fiore','colore',
        'ardore','terrore','furore','onore','errore','sapore','favore',
        'tremore','splendore','candore','orrore','stupore','rumore',
        'vita','ferita','infinita','unita','ambita','sentita','salita',
        'partita','invita','gratuita','smarrita','tradita','scolpita',
      ],
      notte: [
        'notte','grotte','rotte','botte','lotte','dotte',
        'luna','fortuna','bruna','laguna','tribuna','duna','una',
        'voce','croce','noce','atroce','feroce','precoce','veloce',
        'dolce','salce','falce',
      ],
      cielo: [
        'cielo','velo','gelo','bello','quello','anello',
        'castello','uccello','capello','fratello','martello','coltello',
        'sogno','bisogno','ingegno','legno','segno','pegno','degno',
        'tempo','sempre','insieme','estremo','sistema','problema',
      ],
      cuore: [
        'core','ancora','aurora','dimora','signora','lavora','adora',
        'fuori','cuori','tesori','colori','amori','dolori','errori',
        'mare','pare','amare','sperare','trovare','pensare','chiamare',
        'guardare','cercare','tornare','parlare','cantare','volare',
      ],
    },
  };

  // IPA cache for fallback words: lang → Map<word, cleanedIpa>
  const _fbCache   = {};
  const _fbBuilding = {};

  async function _buildFallbackCache(lang) {
    if (_fbCache[lang]) return;
    if (_fbBuilding[lang]) {
      await new Promise((res) => {
        const t = setInterval(() => { if (!_fbBuilding[lang]) { clearInterval(t); res(); } }, 50);
      });
      return;
    }
    _fbBuilding[lang] = true;

    const cats = FALLBACK[lang] || {};
    const allWords = [...new Set(Object.values(cats).flat())];

    // Convert all words at once as a single line for efficiency.
    // IpaConverter.convertLine splits on whitespace → one entry per word.
    const ipaWords = await IpaConverter.convertLine(allWords.join(' '), lang);

    const map = new Map();
    allWords.forEach((w, i) => {
      map.set(w, _cleanIpa(ipaWords[i]?.ipa || ''));
    });
    _fbCache[lang] = map;
    _fbBuilding[lang] = false;
  }

  // ── IPA normalisation (mirrors RhymeDetector.cleanIpa) ──────────────────
  function _cleanIpa(s) {
    return (s || '')
      .replace(/[ˈˌ\/\[\]ː]/g, '')
      .replace(/z/g,  's')
      .replace(/d/g,  't')
      .replace(/b/g,  'p')
      .replace(/ɡ/g,  'k')
      .replace(/v/g,  'f')
      .replace(/ð/g,  'θ')
      .replace(/ʒ/g,  'ʃ')
      .replace(/ə$/,  '')
      .trim();
  }

  function _suffixLen(a, b) {
    let i = a.length - 1, j = b.length - 1, n = 0;
    while (i >= 0 && j >= 0 && a[i] === b[j]) { n++; i--; j--; }
    return n;
  }

  // ── Fallback path: embedded vocabulary + IpaConverter ───────────────────
  function _detectCategories(allLines, currentLine, lang) {
    const cats = FALLBACK[lang] || {};
    const lyricText = allLines
      .filter((l) => l !== currentLine && l.text.trim())
      .map((l) => l.text.toLowerCase())
      .join(' ');

    const matched = new Set();
    for (const [cat, words] of Object.entries(cats)) {
      if (words.some((w) => lyricText.includes(w.toLowerCase()))) matched.add(cat);
    }
    return matched;
  }

  async function _fallbackSuggestions(lineData, allLines) {
    const { lang, ipa, text } = lineData;
    if (!FALLBACK[lang]) return null;

    await _buildFallbackCache(lang);
    const cache   = _fbCache[lang];
    const target  = _cleanIpa(ipa);
    if (!target) return { rich: [], thematic: [] };

    const categories = _detectCategories(allLines, lineData, lang);
    const currentText = text.toLowerCase();
    const cats = FALLBACK[lang];

    const scored = [];
    for (const [cat, words] of Object.entries(cats)) {
      for (const word of words) {
        if (currentText.includes(word.toLowerCase())) continue;
        const wIpa  = cache.get(word) || '';
        const score = _suffixLen(target, wIpa);
        if (score < 1) continue;
        scored.push({ word, score, cat });
      }
    }

    scored.sort((a, b) => b.score - a.score);

    const seen = new Set();
    const unique = scored.filter(({ word }) => { if (seen.has(word)) return false; seen.add(word); return true; });

    const rich    = unique.slice(0, 8).map((s) => s.word);
    const richSet = new Set(rich);

    let thematic;
    if (categories.size > 0) {
      thematic = unique
        .filter((s) => categories.has(s.cat) && !richSet.has(s.word))
        .slice(0, 8)
        .map((s) => s.word);
    } else {
      thematic = unique.filter((s) => !richSet.has(s.word)).slice(0, 8).map((s) => s.word);
    }

    return { rich, thematic };
  }

  // ── Full path: pre-built data + word embeddings ──────────────────────────
  const _index = {};

  function _getData(lang) {
    return window[`WORD_DATA_${lang.toUpperCase()}`] || null;
  }

  function _buildIndex(lang) {
    if (_index[lang]) return;
    const d = _getData(lang);
    if (!d) return;
    const m = new Map();
    d.words.forEach((w, i) => m.set(w.toLowerCase(), i));
    _index[lang] = m;
  }

  function _getVec(data, idx) {
    const { vecs, dim } = data;
    return vecs.subarray(idx * dim, (idx + 1) * dim);
  }

  function _cosineSim(a, b) {
    let dot = 0, na = 0, nb = 0;
    for (let i = 0; i < a.length; i++) { dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; }
    const denom = Math.sqrt(na) * Math.sqrt(nb);
    return denom < 1e-9 ? 0 : dot / denom;
  }

  function _lyricsVector(allLines, currentLine, data, index) {
    const { dim } = data;
    const sum = new Float32Array(dim);
    let count = 0;
    for (const line of allLines) {
      if (line === currentLine || !line.text.trim()) continue;
      for (const tok of line.text.toLowerCase().split(/[\s\-'']+/).map((t) => t.replace(/[^a-zA-ZÀ-ÿœŒ\u0100-\u024F]/g, '')).filter(Boolean)) {
        const idx = index.get(tok);
        if (idx === undefined) continue;
        const vec = _getVec(data, idx);
        for (let i = 0; i < dim; i++) sum[i] += vec[i];
        count++;
      }
    }
    if (count > 0) for (let i = 0; i < dim; i++) sum[i] /= count;
    return { vec: sum, count };
  }

  async function _fullSuggestions(lineData, allLines, data) {
    _buildIndex(lineData.lang);
    const index = _index[lineData.lang];

    const target = _cleanIpa(lineData.ipa);
    if (!target) return { rich: [], thematic: [] };

    const currentText = lineData.text.toLowerCase();
    const { vec: lyricsVec, count: ctxCount } = _lyricsVector(allLines, lineData, data, index);
    const hasContext = ctxCount > 0;

    const N = data.words.length;
    const scored = [];
    for (let i = 0; i < N; i++) {
      const word = data.words[i];
      if (currentText.includes(word.toLowerCase())) continue;
      const wIpa      = _cleanIpa(data.ipa[i] || '');
      const phoneScore = _suffixLen(target, wIpa);
      if (phoneScore < 1) continue;
      const semScore = hasContext ? _cosineSim(lyricsVec, _getVec(data, i)) : 0;
      scored.push({ word, phoneScore, semScore });
    }

    if (scored.length === 0) return { rich: [], thematic: [] };

    scored.sort((a, b) => b.phoneScore - a.phoneScore);

    const rich = [];
    const richSet = new Set();
    for (const s of scored) {
      if (richSet.has(s.word)) continue;
      richSet.add(s.word);
      rich.push(s.word);
      if (rich.length >= 8) break;
    }

    const maxPhone = scored[0].phoneScore || 1;
    const thematic = [];
    if (hasContext) {
      const combined = scored
        .filter((s) => !richSet.has(s.word))
        .map((s) => ({ word: s.word, score: 0.4 * (s.phoneScore / maxPhone) + 0.6 * Math.max(0, s.semScore) }))
        .sort((a, b) => b.score - a.score);
      for (const s of combined) { thematic.push(s.word); if (thematic.length >= 8) break; }
    } else {
      for (const s of scored) {
        if (richSet.has(s.word)) continue;
        thematic.push(s.word);
        if (thematic.length >= 8) break;
      }
    }
    return { rich, thematic };
  }

  // ── Public API ───────────────────────────────────────────────────────────
  async function getSuggestions(lineData, allLines) {
    const data = _getData(lineData.lang);
    if (data) return _fullSuggestions(lineData, allLines, data);
    return _fallbackSuggestions(lineData, allLines);
  }

  return { getSuggestions };
})();
